name: my-app

services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: 1883:1883
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - $PWD/data:/mosquitto/data:rw
      - $PWD/log:/mosquitto/log:rw
      - $PWD/config:/mosquitto/config:ro

